#!/usr/bin/env ruby
require 'io/console'
$bindings = {
  'a' => 'introduction',
  'b' => 'stick'
}
$fifo = 'in'


buff = ''
loop do
  c = STDIN.getch
  if (c == '\\') then
    exit
  elsif (c.match(/[\d]/)) then
    buff += c
  else
    if (buff == '') then
      buff = 1
    end
    sam = $bindings[c]
    if (sam) then
      command = "play #{sam},#{buff}"
      %x[echo #{command} > #{$fifo}]
      puts command
    end
    buff = ''
  end
end
