#!/usr/bin/env ruby
require 'io/console'
$fifo = 'in'

buff = ''
loop do
  c = STDIN.getch
  if (c == '\\') then
    exit
  elsif (c.match(/[\d]/)) then
    buff += c
  else
    if (buff == '') then
      buff = 1
    end

    command = "play #{c},#{buff}"
    %x[echo #{command} > #{$fifo}]
    puts command
    buff = ''
  end
end
